---
Name: socialwallroutes
After:
  - 'weinbauverbandroutes'
---
SilverStripe\Control\Director:
  rules:
    'sociallwallapi//$Action/$ID/$Name': 'NourAlmasrieh\SocialWall\Controllers\SocialPageController'